### ISSUE TITLE
Nats server does not support gateways

### ISSUE THREAD

**Issue by mivanovvs** [bitnami/bitnami-docker-nats#3]
Hi!

I've tried to setup bitnami nats server with configuration with gateways according NATS documentation https://docs.nats.io/nats-server/configuration/gateways#gateway-connections

But it seems bitnami nats does not supports gateways.  
I just put this part in config, but nats is starting as usually and nothing in logs 

```
# gateway definition
gateway {
  listen: 0.0.0.0:7522

  # Authorization for gateways
  authorization {
    user: gwu1
    password: gwp1
  }

  gateways: [
      { name: "me", url: "nats://user:pass@localhost:7522" },
      { name: "another_docker", url: "nats://user:pass@IP:30302" },
      ]
}
```

**Comment by dani8art** [comment]
Hi @mivanovvs ,

I would need more details, could you give a bit more info?

- How are you adding this configuration to your nats container?
- Could you share with us the `docker-compose.yaml` or the docker commands whose are you using? 

Regards.

**Comment by mivanovvs** [comment]
Sorry, it was misconfiguration. But server started with wrong config file and config just was ignored.
