### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by raul-sr** [bitnami/bitnami-docker-nats#4]
Are you going to have a distribution that supports websocket with the commits that are in the nats-server repository?

**Comment by carrodher** [comment]
Hi, we are building our images using the official nats-server source code, so I would say yes, whatever is implemented in the [upstream nats-server repository](https://github.com/nats-io/nats-server) is going to be supported in this Bitnami image.

Having said that, we are not tracking the latest commits in the `master` branch but the releases in https://github.com/nats-io/nats-server/releases. So whenever a new version appears on the releases page, let's say `2.1.8` we start working on release this same version in our Bitnami catalog.
I don't know what is the release frequency of the nats-server projects, but at some point, the commits in `master` are going to be part of a new release, at that moment we'll start working on adding the same version here (depending on the changes included in that new version it may take more or less on our side).
