### ISSUE TITLE
Nats server doesn't expose leafnode port 7422

### ISSUE THREAD

**Issue by c4m4** [bitnami/bitnami-docker-nats#5]
Nats server doesn't expose leafnode port 7422

I trying to use this docker image and enabling the leafnode option it doesn't work

**Comment by juan131** [comment]
Hi @c4m4 

This NATS image uses by default a very simple configuration, see https://github.com/bitnami/bitnami-docker-nats/blob/master/2/debian-10/rootfs/entrypoint.sh

That said, it has support for any custom configuration you want to use. So, in case you want to configure NATS as a LeafNode (see https://docs.nats.io/nats-server/configuration/leafnodes#leafnode-configuration-tutorial), you can simply mount your custom configuration as it's explained in the link below:

- https://github.com/bitnami/bitnami-docker-nats#configuration

**Comment by c4m4** [comment]
@juan131 I solved, I am using kubernetes and modify the helm chart to include leafnodes configuration block was enough

**Comment by juan131** [comment]
Great!! I'm glad you were able to load your custom configuration and make it work!!
Please don't hesitate to let us know if you require further help.
