### ISSUE TITLE
Add Additional Configuration Env

### ISSUE THREAD

**Issue by hotlong** [bitnami/bitnami-docker-nats#7]
### Name and Version

bitnami/bitnami-docker-nats

### What is the problem this feature will solve?

https://docs.nats.io/running-a-nats-service/configuration#limits

### What is the feature you are proposing to solve the problem?

MAX_PAYLOAD for max_payload

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
